name: CI Pipeline

on: 
  pull_request:
    branches:
      - devel
      - stage
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

  steps: 
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: npm run lint

    - name: Run formatter
      run: npm run prettier --write

    - name: Run tests
      run: CI=true npm run test

    - name: Build project
      run: npm run build

    - name: Azure Login action
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    
    - name: "Upload to storage"
      run: |
        az storage blob upload-batch -d '$web' -s ./build --account-name 'develfslstorage'

    - name: "Purge CDN endpoint"
      run: |
        az cdn endpoint purge -g 'develfsl-rg' -n 'devel-fsl-endpoint' --profile-name 'devel-fsl-cdn' --content-paths "/*"
  